package com.tom.trading.remote;

public enum RemoteOpenResult {
    OPENED, STALE, UNAVAILABLE, BUSY, ACCESS_DENIED, PROTECTION_UNAVAILABLE, DISABLED,
    PROTECTION_TARGET_UNLOADED, PROTECTION_PLAYER_UNLOADED, PROTECTION_CLAIM_UNAVAILABLE,
    PROTECTION_VERSION_UNSUPPORTED, PROTECTION_ADAPTER_ERROR,
    REGION_MISSING, REGION_TOO_LARGE, CHUNK_BUDGET_EXHAUSTED, LOAD_TIMEOUT;

    public static RemoteOpenResult denied(com.tom.trading.trade.TradeResultCode result) {
        switch (result) {
        case PROTECTION_UNAVAILABLE: return PROTECTION_UNAVAILABLE;
        case PROTECTION_TARGET_UNLOADED: return PROTECTION_TARGET_UNLOADED;
        case PROTECTION_PLAYER_UNLOADED: return PROTECTION_PLAYER_UNLOADED;
        case PROTECTION_CLAIM_UNAVAILABLE: return PROTECTION_CLAIM_UNAVAILABLE;
        case PROTECTION_VERSION_UNSUPPORTED: return PROTECTION_VERSION_UNSUPPORTED;
        case PROTECTION_ADAPTER_ERROR: return PROTECTION_ADAPTER_ERROR;
        case REMOTE_UNAVAILABLE: return UNAVAILABLE;
        default: return ACCESS_DENIED;
        }
    }
}
