package com.tom.trading.trade;

public enum TradeResultCode {
    SUCCESS,
    INVALID_REQUEST,
    INVALID_OFFER,
    TRADER_MISSING_INPUT,
    MACHINE_MISSING_INPUT,
    TRADER_NO_SPACE,
    MACHINE_NO_SPACE,
    INVARIANT_VIOLATION,
    OFFER_CHANGED,
    RATE_LIMITED,
    SELECTION_TOO_COMPLEX,
    REMOTE_UNAVAILABLE,
    ACCESS_DENIED,
    PROTECTION_UNAVAILABLE,
    PROTECTION_TARGET_UNLOADED,
    PROTECTION_PLAYER_UNLOADED,
    PROTECTION_CLAIM_UNAVAILABLE,
    PROTECTION_VERSION_UNSUPPORTED,
    PROTECTION_ADAPTER_ERROR
}
